question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "Sharks are the only fish that can blink with both eyes.", "answer": "False"},
    {"text": "The unicorn is the national animal of Scotland.", "answer": "True"},
    {"text": "Octopuses have three hearts.", "answer": "True"},
    {"text": "The Great Wall of China is visible from space.", "answer": "False"},
    {"text": "Honey never spoils.", "answer": "True"},
    {"text": "The first product with a barcode was chewing gum.", "answer": "False"},
    {"text": "A group of flamingos is called a 'flamboyance'.", "answer": "True"},
    {"text": "The human body has four lungs.", "answer": "False"},
    {"text": "The Eiffel Tower can be 15 cm taller during the summer.", "answer": "True"},
    {"text": "Goldfish only have a memory span of three seconds.", "answer": "False"},
    {"text": "The longest wedding veil was longer than 60 football fields.", "answer": "True"},
    {"text": "The inventor of the lightbulb was Thomas Edison.", "answer": "True"},
    {"text": "The first computer virus was created in the 1980s.", "answer": "True"},
    {"text": "The Amazon rainforest produces 20% of the world's oxygen.", "answer": "False"},
    {"text": "The dot over the letter 'i' is called a tittle.", "answer": "True"},
    {"text": "Humans share 50% of their DNA with bananas.", "answer": "True"},
    {"text": "The longest hiccuping spree lasted 68 years.", "answer": "True"}
]